title: IS-403 Optical sensor for precision agriculture
description: IS-403 Report for Optical sensor for precision agriculture
theme: just-the-docs

url: https://redtree76.github.io

baseurl: "/IS-403-final"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

nav_enabled: true
heading_anchors: true
