title: IS-403 Optical sensor for precision agriculture
description: IS-403 Report for Optical sensor for precision agriculture

remote_theme: just-the-docs/just-the-docs

url: https://redtree76.github.io/IS-403-final

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

nav_enabled: true
heading_anchors: true




